// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ArrowDropDownIcon as MuiArrowDropDownIcon } from '@mui/x-date-pickers'

const ArrowDropDownIcon = createMuiNode(MuiArrowDropDownIcon)
export default ArrowDropDownIcon
