// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ArrowLeftIcon as MuiArrowLeftIcon } from '@mui/x-date-pickers'

const ArrowLeftIcon = createMuiNode(MuiArrowLeftIcon)
export default ArrowLeftIcon
