// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ClearIcon as MuiClearIcon } from '@mui/x-date-pickers'

const ClearIcon = createMuiNode(MuiClearIcon)
export default ClearIcon
