// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DateTimePickerTabs as MuiDateTimePickerTabs } from '@mui/x-date-pickers'

const DateTimePickerTabs = createMuiNode(MuiDateTimePickerTabs)
export default DateTimePickerTabs
