// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DateTimePickerToolbar as MuiDateTimePickerToolbar } from '@mui/x-date-pickers'

const DateTimePickerToolbar = createMuiNode(MuiDateTimePickerToolbar)
export default DateTimePickerToolbar
