// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DateRangeIcon as MuiDateRangeIcon } from '@mui/x-date-pickers'

const DateRangeIcon = createMuiNode(MuiDateRangeIcon)
export default DateRangeIcon
