// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DatePickerToolbar as MuiDatePickerToolbar } from '@mui/x-date-pickers'

const DatePickerToolbar = createMuiNode(MuiDatePickerToolbar)
export default DatePickerToolbar
