// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DateTimeField as MuiDateTimeField } from '@mui/x-date-pickers'

const DateTimeField = createMuiNode(MuiDateTimeField)
export default DateTimeField
