// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DesktopTimePicker as MuiDesktopTimePicker } from '@mui/x-date-pickers'

const DesktopTimePicker = createMuiNode(MuiDesktopTimePicker)
export default DesktopTimePicker
