// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DesktopDateTimePicker as MuiDesktopDateTimePicker } from '@mui/x-date-pickers'

const DesktopDateTimePicker = createMuiNode(MuiDesktopDateTimePicker)
export default DesktopDateTimePicker
