// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DigitalClockItem as MuiDigitalClockItem } from '@mui/x-date-pickers'

const DigitalClockItem = createMuiNode(MuiDigitalClockItem)
export default DigitalClockItem
