// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { LocalizationProvider as MuiLocalizationProvider } from '@mui/x-date-pickers'

const LocalizationProvider = createMuiNode(MuiLocalizationProvider)
export default LocalizationProvider
