// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { MultiSectionDigitalClock as MuiMultiSectionDigitalClock } from '@mui/x-date-pickers'

const MultiSectionDigitalClock = createMuiNode(MuiMultiSectionDigitalClock)
export default MultiSectionDigitalClock
