// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PickersInputBase as MuiPickersInputBase } from '@mui/x-date-pickers'

const PickersInputBase = createMuiNode(MuiPickersInputBase)
export default PickersInputBase
