// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PickerDay as MuiPickerDay } from '@mui/x-date-pickers'

const PickerDay = createMuiNode(MuiPickerDay)
export default PickerDay
