// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PickersInput as MuiPickersInput } from '@mui/x-date-pickers'

const PickersInput = createMuiNode(MuiPickersInput)
export default PickersInput
