// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PickersLayoutContentWrapper as MuiPickersLayoutContentWrapper } from '@mui/x-date-pickers'

const PickersLayoutContentWrapper = createMuiNode(MuiPickersLayoutContentWrapper)
export default PickersLayoutContentWrapper
