// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode, type WrappedMui } from '@src/core.js'
import { PickersTextField as MuiPickersTextField } from '@mui/x-date-pickers'

const PickersTextField: WrappedMui<typeof MuiPickersTextField> = createMuiNode(MuiPickersTextField)
export default PickersTextField
