// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PickersOutlinedInput as MuiPickersOutlinedInput } from '@mui/x-date-pickers'

const PickersOutlinedInput = createMuiNode(MuiPickersOutlinedInput)
export default PickersOutlinedInput
