// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PickersCalendarHeader as MuiPickersCalendarHeader } from '@mui/x-date-pickers'

const PickersCalendarHeader = createMuiNode(MuiPickersCalendarHeader)
export default PickersCalendarHeader
