// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { StaticDatePicker as MuiStaticDatePicker } from '@mui/x-date-pickers'

const StaticDatePicker = createMuiNode(MuiStaticDatePicker)
export default StaticDatePicker
