// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { StaticDateTimePicker as MuiStaticDateTimePicker } from '@mui/x-date-pickers'

const StaticDateTimePicker = createMuiNode(MuiStaticDateTimePicker)
export default StaticDateTimePicker
