// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TimeField as MuiTimeField } from '@mui/x-date-pickers'

const TimeField = createMuiNode(MuiTimeField)
export default TimeField
