// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { YearCalendar as MuiYearCalendar } from '@mui/x-date-pickers'

const YearCalendar = createMuiNode(MuiYearCalendar)
export default YearCalendar
