// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { AnimatedArea as MuiAnimatedArea } from '@mui/x-charts-pro'

const AnimatedArea = createMuiNode(MuiAnimatedArea)
export default AnimatedArea
