// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { BarChartPro as MuiBarChartPro } from '@mui/x-charts-pro'

const BarChartPro = createMuiNode(MuiBarChartPro)
export default BarChartPro
