// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { BarChart as MuiBarChart } from '@mui/x-charts-pro'

const BarChart = createMuiNode(MuiBarChart)
export default BarChart
