// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { BarLabel as MuiBarLabel } from '@mui/x-charts-pro'

const BarLabel = createMuiNode(MuiBarLabel)
export default BarLabel
