// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { BarPlot as MuiBarPlot } from '@mui/x-charts-pro'

const BarPlot = createMuiNode(MuiBarPlot)
export default BarPlot
