// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsAxis as MuiChartsAxis } from '@mui/x-charts-pro'

const ChartsAxis = createMuiNode(MuiChartsAxis)
export default ChartsAxis
