// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsXAxis as MuiChartsXAxis } from '@mui/x-charts-pro'

const ChartsXAxis = createMuiNode(MuiChartsXAxis)
export default ChartsXAxis
