// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode, type WrappedMui } from '@src/core.js'
import { ChartsToolbarZoomOutTrigger as MuiChartsToolbarZoomOutTrigger } from '@mui/x-charts-pro'

const ChartsToolbarZoomOutTrigger: WrappedMui<typeof MuiChartsToolbarZoomOutTrigger> = createMuiNode(MuiChartsToolbarZoomOutTrigger)
export default ChartsToolbarZoomOutTrigger
