// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsToolbarImageExportTrigger as MuiChartsToolbarImageExportTrigger } from '@mui/x-charts-pro'

const ChartsToolbarImageExportTrigger = createMuiNode(MuiChartsToolbarImageExportTrigger)
export default ChartsToolbarImageExportTrigger
