// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsOverlay as MuiChartsOverlay } from '@mui/x-charts-pro'

const ChartsOverlay = createMuiNode(MuiChartsOverlay)
export default ChartsOverlay
