// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsZoomSlider as MuiChartsZoomSlider } from '@mui/x-charts-pro'

const ChartsZoomSlider = createMuiNode(MuiChartsZoomSlider)
export default ChartsZoomSlider
