// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsTooltipPaper as MuiChartsTooltipPaper } from '@mui/x-charts-pro'

const ChartsTooltipPaper = createMuiNode(MuiChartsTooltipPaper)
export default ChartsTooltipPaper
