// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsAxisTooltipContent as MuiChartsAxisTooltipContent } from '@mui/x-charts-pro'

const ChartsAxisTooltipContent = createMuiNode(MuiChartsAxisTooltipContent)
export default ChartsAxisTooltipContent
