// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsTooltipTable as MuiChartsTooltipTable } from '@mui/x-charts-pro'

const ChartsTooltipTable = createMuiNode(MuiChartsTooltipTable)
export default ChartsTooltipTable
