// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsLocalizationProvider as MuiChartsLocalizationProvider } from '@mui/x-charts-pro'

const ChartsLocalizationProvider = createMuiNode(MuiChartsLocalizationProvider)
export default ChartsLocalizationProvider
