// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsReferenceLine as MuiChartsReferenceLine } from '@mui/x-charts-pro'

const ChartsReferenceLine = createMuiNode(MuiChartsReferenceLine)
export default ChartsReferenceLine
