// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsToolbarPro as MuiChartsToolbarPro } from '@mui/x-charts-pro'

const ChartsToolbarPro = createMuiNode(MuiChartsToolbarPro)
export default ChartsToolbarPro
