// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsLegend as MuiChartsLegend } from '@mui/x-charts-pro'

const ChartsLegend = createMuiNode(MuiChartsLegend)
export default ChartsLegend
