// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsTooltip as MuiChartsTooltip } from '@mui/x-charts-pro'

const ChartsTooltip = createMuiNode(MuiChartsTooltip)
export default ChartsTooltip
