// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsTooltipCell as MuiChartsTooltipCell } from '@mui/x-charts-pro'

const ChartsTooltipCell = createMuiNode(MuiChartsTooltipCell)
export default ChartsTooltipCell
