// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsNoDataOverlay as MuiChartsNoDataOverlay } from '@mui/x-charts-pro'

const ChartsNoDataOverlay = createMuiNode(MuiChartsNoDataOverlay)
export default ChartsNoDataOverlay
