// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartZoomSlider as MuiChartZoomSlider } from '@mui/x-charts-pro'

const ChartZoomSlider = createMuiNode(MuiChartZoomSlider)
export default ChartZoomSlider
