// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsDataProviderPro as MuiChartsDataProviderPro } from '@mui/x-charts-pro'

const ChartsDataProviderPro = createMuiNode(MuiChartsDataProviderPro)
export default ChartsDataProviderPro
