// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsRadialDataProvider as MuiChartsRadialDataProvider } from '@mui/x-charts-pro'

const ChartsRadialDataProvider = createMuiNode(MuiChartsRadialDataProvider)
export default ChartsRadialDataProvider
