// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsToolbarPrintExportTrigger as MuiChartsToolbarPrintExportTrigger } from '@mui/x-charts-pro'

const ChartsToolbarPrintExportTrigger = createMuiNode(MuiChartsToolbarPrintExportTrigger)
export default ChartsToolbarPrintExportTrigger
