// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsBrushOverlay as MuiChartsBrushOverlay } from '@mui/x-charts-pro'

const ChartsBrushOverlay = createMuiNode(MuiChartsBrushOverlay)
export default ChartsBrushOverlay
