// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsDataProvider as MuiChartsDataProvider } from '@mui/x-charts-pro'

const ChartsDataProvider = createMuiNode(MuiChartsDataProvider)
export default ChartsDataProvider
