// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsAxisHighlight as MuiChartsAxisHighlight } from '@mui/x-charts-pro'

const ChartsAxisHighlight = createMuiNode(MuiChartsAxisHighlight)
export default ChartsAxisHighlight
