// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsToolbarRangeButtonTrigger as MuiChartsToolbarRangeButtonTrigger } from '@mui/x-charts-pro'

const ChartsToolbarRangeButtonTrigger = createMuiNode(MuiChartsToolbarRangeButtonTrigger)
export default ChartsToolbarRangeButtonTrigger
