// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsClipPath as MuiChartsClipPath } from '@mui/x-charts-pro'

const ChartsClipPath = createMuiNode(MuiChartsClipPath)
export default ChartsClipPath
