// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { FocusedRadarMark as MuiFocusedRadarMark } from '@mui/x-charts-pro'

const FocusedRadarMark = createMuiNode(MuiFocusedRadarMark)
export default FocusedRadarMark
