// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { FocusedPieArc as MuiFocusedPieArc } from '@mui/x-charts-pro'

const FocusedPieArc = createMuiNode(MuiFocusedPieArc)
export default FocusedPieArc
