// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { FocusedSankeyNode as MuiFocusedSankeyNode } from '@mui/x-charts-pro'

const FocusedSankeyNode = createMuiNode(MuiFocusedSankeyNode)
export default FocusedSankeyNode
