// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { FocusedHeatmapCell as MuiFocusedHeatmapCell } from '@mui/x-charts-pro'

const FocusedHeatmapCell = createMuiNode(MuiFocusedHeatmapCell)
export default FocusedHeatmapCell
