// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { FocusedFunnelSection as MuiFocusedFunnelSection } from '@mui/x-charts-pro'

const FocusedFunnelSection = createMuiNode(MuiFocusedFunnelSection)
export default FocusedFunnelSection
