// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { FocusedSankeyLink as MuiFocusedSankeyLink } from '@mui/x-charts-pro'

const FocusedSankeyLink = createMuiNode(MuiFocusedSankeyLink)
export default FocusedSankeyLink
