// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { FocusedScatterMark as MuiFocusedScatterMark } from '@mui/x-charts-pro'

const FocusedScatterMark = createMuiNode(MuiFocusedScatterMark)
export default FocusedScatterMark
