// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { FunnelPlot as MuiFunnelPlot } from '@mui/x-charts-pro'

const FunnelPlot = createMuiNode(MuiFunnelPlot)
export default FunnelPlot
