// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { FunnelChart as MuiFunnelChart } from '@mui/x-charts-pro'

const FunnelChart = createMuiNode(MuiFunnelChart)
export default FunnelChart
