// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GaugeValueText as MuiGaugeValueText } from '@mui/x-charts-pro'

const GaugeValueText = createMuiNode(MuiGaugeValueText)
export default GaugeValueText
