// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { HeatmapPlot as MuiHeatmapPlot } from '@mui/x-charts-pro'

const HeatmapPlot = createMuiNode(MuiHeatmapPlot)
export default HeatmapPlot
