// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { HeatmapCell as MuiHeatmapCell } from '@mui/x-charts-pro'

const HeatmapCell = createMuiNode(MuiHeatmapCell)
export default HeatmapCell
