// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { HeatmapTooltip as MuiHeatmapTooltip } from '@mui/x-charts-pro'

const HeatmapTooltip = createMuiNode(MuiHeatmapTooltip)
export default HeatmapTooltip
