// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Heatmap as MuiHeatmap } from '@mui/x-charts-pro'

const Heatmap = createMuiNode(MuiHeatmap)
export default Heatmap
