// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { HeatmapTooltipContent as MuiHeatmapTooltipContent } from '@mui/x-charts-pro'

const HeatmapTooltipContent = createMuiNode(MuiHeatmapTooltipContent)
export default HeatmapTooltipContent
