// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { LinePlot as MuiLinePlot } from '@mui/x-charts-pro'

const LinePlot = createMuiNode(MuiLinePlot)
export default LinePlot
