// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { LineHighlightPlot as MuiLineHighlightPlot } from '@mui/x-charts-pro'

const LineHighlightPlot = createMuiNode(MuiLineHighlightPlot)
export default LineHighlightPlot
