// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { LineChartPro as MuiLineChartPro } from '@mui/x-charts-pro'

const LineChartPro = createMuiNode(MuiLineChartPro)
export default LineChartPro
