// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { LineHighlightElement as MuiLineHighlightElement } from '@mui/x-charts-pro'

const LineHighlightElement = createMuiNode(MuiLineHighlightElement)
export default LineHighlightElement
