// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { MarkPlot as MuiMarkPlot } from '@mui/x-charts-pro'

const MarkPlot = createMuiNode(MuiMarkPlot)
export default MarkPlot
