// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PieArcLabelPlot as MuiPieArcLabelPlot } from '@mui/x-charts-pro'

const PieArcLabelPlot = createMuiNode(MuiPieArcLabelPlot)
export default PieArcLabelPlot
