// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PieArcPlot as MuiPieArcPlot } from '@mui/x-charts-pro'

const PieArcPlot = createMuiNode(MuiPieArcPlot)
export default PieArcPlot
