// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PiecewiseColorLegend as MuiPiecewiseColorLegend } from '@mui/x-charts-pro'

const PiecewiseColorLegend = createMuiNode(MuiPiecewiseColorLegend)
export default PiecewiseColorLegend
