// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PieChartPro as MuiPieChartPro } from '@mui/x-charts-pro'

const PieChartPro = createMuiNode(MuiPieChartPro)
export default PieChartPro
