// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { RadarChartPro as MuiRadarChartPro } from '@mui/x-charts-pro'

const RadarChartPro = createMuiNode(MuiRadarChartPro)
export default RadarChartPro
