// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { RadarChart as MuiRadarChart } from '@mui/x-charts-pro'

const RadarChart = createMuiNode(MuiRadarChart)
export default RadarChart
