// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { RadarMetricLabels as MuiRadarMetricLabels } from '@mui/x-charts-pro'

const RadarMetricLabels = createMuiNode(MuiRadarMetricLabels)
export default RadarMetricLabels
