// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { RadarAxis as MuiRadarAxis } from '@mui/x-charts-pro'

const RadarAxis = createMuiNode(MuiRadarAxis)
export default RadarAxis
