// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { RadarSeriesMarks as MuiRadarSeriesMarks } from '@mui/x-charts-pro'

const RadarSeriesMarks = createMuiNode(MuiRadarSeriesMarks)
export default RadarSeriesMarks
