// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { RadarDataProvider as MuiRadarDataProvider } from '@mui/x-charts-pro'

const RadarDataProvider = createMuiNode(MuiRadarDataProvider)
export default RadarDataProvider
