// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { RadarGrid as MuiRadarGrid } from '@mui/x-charts-pro'

const RadarGrid = createMuiNode(MuiRadarGrid)
export default RadarGrid
