// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { RadarAxisHighlight as MuiRadarAxisHighlight } from '@mui/x-charts-pro'

const RadarAxisHighlight = createMuiNode(MuiRadarAxisHighlight)
export default RadarAxisHighlight
