// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { SankeyPlot as MuiSankeyPlot } from '@mui/x-charts-pro'

const SankeyPlot = createMuiNode(MuiSankeyPlot)
export default SankeyPlot
