// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { SankeyChart as MuiSankeyChart } from '@mui/x-charts-pro'

const SankeyChart = createMuiNode(MuiSankeyChart)
export default SankeyChart
