// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { SankeyNodePlot as MuiSankeyNodePlot } from '@mui/x-charts-pro'

const SankeyNodePlot = createMuiNode(MuiSankeyNodePlot)
export default SankeyNodePlot
