// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { SankeyTooltipContent as MuiSankeyTooltipContent } from '@mui/x-charts-pro'

const SankeyTooltipContent = createMuiNode(MuiSankeyTooltipContent)
export default SankeyTooltipContent
