// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { SankeyNodeLabelPlot as MuiSankeyNodeLabelPlot } from '@mui/x-charts-pro'

const SankeyNodeLabelPlot = createMuiNode(MuiSankeyNodeLabelPlot)
export default SankeyNodeLabelPlot
