// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { SankeyDataProvider as MuiSankeyDataProvider } from '@mui/x-charts-pro'

const SankeyDataProvider = createMuiNode(MuiSankeyDataProvider)
export default SankeyDataProvider
