// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { SankeyLinkPlot as MuiSankeyLinkPlot } from '@mui/x-charts-pro'

const SankeyLinkPlot = createMuiNode(MuiSankeyLinkPlot)
export default SankeyLinkPlot
