// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Scatter as MuiScatter } from '@mui/x-charts-pro'

const Scatter = createMuiNode(MuiScatter)
export default Scatter
