// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ScatterPlot as MuiScatterPlot } from '@mui/x-charts-pro'

const ScatterPlot = createMuiNode(MuiScatterPlot)
export default ScatterPlot
