// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { SparkLineChart as MuiSparkLineChart } from '@mui/x-charts-pro'

const SparkLineChart = createMuiNode(MuiSparkLineChart)
export default SparkLineChart
