// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ExportCsv as MuiExportCsv } from '@mui/x-data-grid'

const ExportCsv = createMuiNode(MuiExportCsv)
export default ExportCsv
