// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { FilterPanelTrigger as MuiFilterPanelTrigger } from '@mui/x-data-grid'

const FilterPanelTrigger = createMuiNode(MuiFilterPanelTrigger)
export default FilterPanelTrigger
