// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode, type WrappedMui } from '@src/core.js'
import { GridColumnHeaderSeparator as MuiGridColumnHeaderSeparator } from '@mui/x-data-grid'

const GridColumnHeaderSeparator: WrappedMui<typeof MuiGridColumnHeaderSeparator> = createMuiNode(MuiGridColumnHeaderSeparator)
export default GridColumnHeaderSeparator
