// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridShadowScrollArea as MuiGridShadowScrollArea } from '@mui/x-data-grid'

const GridShadowScrollArea = createMuiNode(MuiGridShadowScrollArea)
export default GridShadowScrollArea
