// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridCheckIcon as MuiGridCheckIcon } from '@mui/x-data-grid'

const GridCheckIcon = createMuiNode(MuiGridCheckIcon)
export default GridCheckIcon
