// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridColumnMenuHideItem as MuiGridColumnMenuHideItem } from '@mui/x-data-grid'

const GridColumnMenuHideItem = createMuiNode(MuiGridColumnMenuHideItem)
export default GridColumnMenuHideItem
