// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridDownloadIcon as MuiGridDownloadIcon } from '@mui/x-data-grid'

const GridDownloadIcon = createMuiNode(MuiGridDownloadIcon)
export default GridDownloadIcon
