// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridPanelFooter as MuiGridPanelFooter } from '@mui/x-data-grid'

const GridPanelFooter = createMuiNode(MuiGridPanelFooter)
export default GridPanelFooter
