// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridToolbar as MuiGridToolbar } from '@mui/x-data-grid'

const GridToolbar = createMuiNode(MuiGridToolbar)
export default GridToolbar
