// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridActionsCell as MuiGridActionsCell } from '@mui/x-data-grid'

const GridActionsCell = createMuiNode(MuiGridActionsCell)
export default GridActionsCell
