// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridRow as MuiGridRow } from '@mui/x-data-grid'

const GridRow = createMuiNode(MuiGridRow)
export default GridRow
