// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridFilterInputMultipleSingleSelect as MuiGridFilterInputMultipleSingleSelect } from '@mui/x-data-grid'

const GridFilterInputMultipleSingleSelect = createMuiNode(MuiGridFilterInputMultipleSingleSelect)
export default GridFilterInputMultipleSingleSelect
