// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridColumnMenu as MuiGridColumnMenu } from '@mui/x-data-grid'

const GridColumnMenu = createMuiNode(MuiGridColumnMenu)
export default GridColumnMenu
