// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridMenu as MuiGridMenu } from '@mui/x-data-grid'

const GridMenu = createMuiNode(MuiGridMenu)
export default GridMenu
