// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridColumnHeaderFilterIconButton as MuiGridColumnHeaderFilterIconButton } from '@mui/x-data-grid'

const GridColumnHeaderFilterIconButton = createMuiNode(MuiGridColumnHeaderFilterIconButton)
export default GridColumnHeaderFilterIconButton
