// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridColumnsPanel as MuiGridColumnsPanel } from '@mui/x-data-grid'

const GridColumnsPanel = createMuiNode(MuiGridColumnsPanel)
export default GridColumnsPanel
