// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridCell as MuiGridCell } from '@mui/x-data-grid'

const GridCell = createMuiNode(MuiGridCell)
export default GridCell
