// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridToolbarExport as MuiGridToolbarExport } from '@mui/x-data-grid'

const GridToolbarExport = createMuiNode(MuiGridToolbarExport)
export default GridToolbarExport
