// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridAddIcon as MuiGridAddIcon } from '@mui/x-data-grid'

const GridAddIcon = createMuiNode(MuiGridAddIcon)
export default GridAddIcon
