// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode, type WrappedMui } from '@src/core.js'
import { GridBooleanCell as MuiGridBooleanCell } from '@mui/x-data-grid'

const GridBooleanCell: WrappedMui<typeof MuiGridBooleanCell> = createMuiNode(MuiGridBooleanCell)
export default GridBooleanCell
