// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridExpandMoreIcon as MuiGridExpandMoreIcon } from '@mui/x-data-grid'

const GridExpandMoreIcon = createMuiNode(MuiGridExpandMoreIcon)
export default GridExpandMoreIcon
