// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridSeparatorIcon as MuiGridSeparatorIcon } from '@mui/x-data-grid'

const GridSeparatorIcon = createMuiNode(MuiGridSeparatorIcon)
export default GridSeparatorIcon
