// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridColumnsManagement as MuiGridColumnsManagement } from '@mui/x-data-grid'

const GridColumnsManagement = createMuiNode(MuiGridColumnsManagement)
export default GridColumnsManagement
