// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridPortalWrapper as MuiGridPortalWrapper } from '@mui/x-data-grid'

const GridPortalWrapper = createMuiNode(MuiGridPortalWrapper)
export default GridPortalWrapper
