// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridLoadIcon as MuiGridLoadIcon } from '@mui/x-data-grid'

const GridLoadIcon = createMuiNode(MuiGridLoadIcon)
export default GridLoadIcon
