// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridToolbarFilterButton as MuiGridToolbarFilterButton } from '@mui/x-data-grid'

const GridToolbarFilterButton = createMuiNode(MuiGridToolbarFilterButton)
export default GridToolbarFilterButton
