// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridColumnMenuColumnsItem as MuiGridColumnMenuColumnsItem } from '@mui/x-data-grid'

const GridColumnMenuColumnsItem = createMuiNode(MuiGridColumnMenuColumnsItem)
export default GridColumnMenuColumnsItem
