// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridFilterAltIcon as MuiGridFilterAltIcon } from '@mui/x-data-grid'

const GridFilterAltIcon = createMuiNode(MuiGridFilterAltIcon)
export default GridFilterAltIcon
