// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridFilterListIcon as MuiGridFilterListIcon } from '@mui/x-data-grid'

const GridFilterListIcon = createMuiNode(MuiGridFilterListIcon)
export default GridFilterListIcon
