// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridPrintExportMenuItem as MuiGridPrintExportMenuItem } from '@mui/x-data-grid'

const GridPrintExportMenuItem = createMuiNode(MuiGridPrintExportMenuItem)
export default GridPrintExportMenuItem
