// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridPanelContent as MuiGridPanelContent } from '@mui/x-data-grid'

const GridPanelContent = createMuiNode(MuiGridPanelContent)
export default GridPanelContent
