// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { QuickFilter as MuiQuickFilter } from '@mui/x-data-grid'

const QuickFilter = createMuiNode(MuiQuickFilter)
export default QuickFilter
