// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { QuickFilterControl as MuiQuickFilterControl } from '@mui/x-data-grid'

const QuickFilterControl = createMuiNode(MuiQuickFilterControl)
export default QuickFilterControl
