// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { AnimatedLine as MuiAnimatedLine } from '@mui/x-charts'

const AnimatedLine = createMuiNode(MuiAnimatedLine)
export default AnimatedLine
