// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { AreaElement as MuiAreaElement } from '@mui/x-charts'

const AreaElement = createMuiNode(MuiAreaElement)
export default AreaElement
