// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { BarElement as MuiBarElement } from '@mui/x-charts'

const BarElement = createMuiNode(MuiBarElement)
export default BarElement
