// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsSurface as MuiChartsSurface } from '@mui/x-charts'

const ChartsSurface = createMuiNode(MuiChartsSurface)
export default ChartsSurface
