// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsLayerContainer as MuiChartsLayerContainer } from '@mui/x-charts'

const ChartsLayerContainer = createMuiNode(MuiChartsLayerContainer)
export default ChartsLayerContainer
