// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsAxisHighlightValue as MuiChartsAxisHighlightValue } from '@mui/x-charts'

const ChartsAxisHighlightValue = createMuiNode(MuiChartsAxisHighlightValue)
export default ChartsAxisHighlightValue
