// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsWrapper as MuiChartsWrapper } from '@mui/x-charts'

const ChartsWrapper = createMuiNode(MuiChartsWrapper)
export default ChartsWrapper
