// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsRadialAxisHighlightPath as MuiChartsRadialAxisHighlightPath } from '@mui/x-charts'

const ChartsRadialAxisHighlightPath = createMuiNode(MuiChartsRadialAxisHighlightPath)
export default ChartsRadialAxisHighlightPath
