// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsTooltipRow as MuiChartsTooltipRow } from '@mui/x-charts'

const ChartsTooltipRow = createMuiNode(MuiChartsTooltipRow)
export default ChartsTooltipRow
