// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsItemTooltipContent as MuiChartsItemTooltipContent } from '@mui/x-charts'

const ChartsItemTooltipContent = createMuiNode(MuiChartsItemTooltipContent)
export default ChartsItemTooltipContent
