// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsLabelMark as MuiChartsLabelMark } from '@mui/x-charts'

const ChartsLabelMark = createMuiNode(MuiChartsLabelMark)
export default ChartsLabelMark
