// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsText as MuiChartsText } from '@mui/x-charts'

const ChartsText = createMuiNode(MuiChartsText)
export default ChartsText
