// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsRadialAxisHighlightCircle as MuiChartsRadialAxisHighlightCircle } from '@mui/x-charts'

const ChartsRadialAxisHighlightCircle = createMuiNode(MuiChartsRadialAxisHighlightCircle)
export default ChartsRadialAxisHighlightCircle
