// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsLabel as MuiChartsLabel } from '@mui/x-charts'

const ChartsLabel = createMuiNode(MuiChartsLabel)
export default ChartsLabel
