// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsRadiusAxis as MuiChartsRadiusAxis } from '@mui/x-charts'

const ChartsRadiusAxis = createMuiNode(MuiChartsRadiusAxis)
export default ChartsRadiusAxis
