// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsAxisHighlightPath as MuiChartsAxisHighlightPath } from '@mui/x-charts'

const ChartsAxisHighlightPath = createMuiNode(MuiChartsAxisHighlightPath)
export default ChartsAxisHighlightPath
