// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsSvgLayer as MuiChartsSvgLayer } from '@mui/x-charts'

const ChartsSvgLayer = createMuiNode(MuiChartsSvgLayer)
export default ChartsSvgLayer
