// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsYAxis as MuiChartsYAxis } from '@mui/x-charts'

const ChartsYAxis = createMuiNode(MuiChartsYAxis)
export default ChartsYAxis
