// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsTooltipContainer as MuiChartsTooltipContainer } from '@mui/x-charts'

const ChartsTooltipContainer = createMuiNode(MuiChartsTooltipContainer)
export default ChartsTooltipContainer
