// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsRadialGrid as MuiChartsRadialGrid } from '@mui/x-charts'

const ChartsRadialGrid = createMuiNode(MuiChartsRadialGrid)
export default ChartsRadialGrid
