// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsGrid as MuiChartsGrid } from '@mui/x-charts'

const ChartsGrid = createMuiNode(MuiChartsGrid)
export default ChartsGrid
