// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsRadialAxisHighlight as MuiChartsRadialAxisHighlight } from '@mui/x-charts'

const ChartsRadialAxisHighlight = createMuiNode(MuiChartsRadialAxisHighlight)
export default ChartsRadialAxisHighlight
