// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsContainer as MuiChartsContainer } from '@mui/x-charts'

const ChartsContainer = createMuiNode(MuiChartsContainer)
export default ChartsContainer
