// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ContinuousColorLegend as MuiContinuousColorLegend } from '@mui/x-charts'

const ContinuousColorLegend = createMuiNode(MuiContinuousColorLegend)
export default ContinuousColorLegend
