// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { FocusedLineMark as MuiFocusedLineMark } from '@mui/x-charts'

const FocusedLineMark = createMuiNode(MuiFocusedLineMark)
export default FocusedLineMark
