// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { FocusedBar as MuiFocusedBar } from '@mui/x-charts'

const FocusedBar = createMuiNode(MuiFocusedBar)
export default FocusedBar
