// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GaugeValueArc as MuiGaugeValueArc } from '@mui/x-charts'

const GaugeValueArc = createMuiNode(MuiGaugeValueArc)
export default GaugeValueArc
