// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GaugeReferenceArc as MuiGaugeReferenceArc } from '@mui/x-charts'

const GaugeReferenceArc = createMuiNode(MuiGaugeReferenceArc)
export default GaugeReferenceArc
