// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Gauge as MuiGauge } from '@mui/x-charts'

const Gauge = createMuiNode(MuiGauge)
export default Gauge
