// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GaugeContainer as MuiGaugeContainer } from '@mui/x-charts'

const GaugeContainer = createMuiNode(MuiGaugeContainer)
export default GaugeContainer
