// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { HighlightedScatterMark as MuiHighlightedScatterMark } from '@mui/x-charts'

const HighlightedScatterMark = createMuiNode(MuiHighlightedScatterMark)
export default HighlightedScatterMark
