// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { LineElement as MuiLineElement } from '@mui/x-charts'

const LineElement = createMuiNode(MuiLineElement)
export default LineElement
