// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { LineChart as MuiLineChart } from '@mui/x-charts'

const LineChart = createMuiNode(MuiLineChart)
export default LineChart
