// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { MarkElement as MuiMarkElement } from '@mui/x-charts'

const MarkElement = createMuiNode(MuiMarkElement)
export default MarkElement
