// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PieChart as MuiPieChart } from '@mui/x-charts'

const PieChart = createMuiNode(MuiPieChart)
export default PieChart
