// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PiePlot as MuiPiePlot } from '@mui/x-charts'

const PiePlot = createMuiNode(MuiPiePlot)
export default PiePlot
