// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { RadarSeriesPlot as MuiRadarSeriesPlot } from '@mui/x-charts'

const RadarSeriesPlot = createMuiNode(MuiRadarSeriesPlot)
export default RadarSeriesPlot
