// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { RadarSeriesArea as MuiRadarSeriesArea } from '@mui/x-charts'

const RadarSeriesArea = createMuiNode(MuiRadarSeriesArea)
export default RadarSeriesArea
