// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ScatterChart as MuiScatterChart } from '@mui/x-charts'

const ScatterChart = createMuiNode(MuiScatterChart)
export default ScatterChart
