// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ScatterMarker as MuiScatterMarker } from '@mui/x-charts'

const ScatterMarker = createMuiNode(MuiScatterMarker)
export default ScatterMarker
