// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Accordion as MuiAccordion } from '@mui/material'

const Accordion = createMuiNode(MuiAccordion)
export default Accordion
