// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { AccordionActions as MuiAccordionActions } from '@mui/material'

const AccordionActions = createMuiNode(MuiAccordionActions)
export default AccordionActions
