// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { AccordionDetails as MuiAccordionDetails } from '@mui/material'

const AccordionDetails = createMuiNode(MuiAccordionDetails)
export default AccordionDetails
