// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { AccordionSummary as MuiAccordionSummary } from '@mui/material'

const AccordionSummary = createMuiNode(MuiAccordionSummary)
export default AccordionSummary
