// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { AlertTitle as MuiAlertTitle } from '@mui/material'

const AlertTitle = createMuiNode(MuiAlertTitle)
export default AlertTitle
