// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Alert as MuiAlert } from '@mui/material'

const Alert = createMuiNode(MuiAlert)
export default Alert
