// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { AppBar as MuiAppBar } from '@mui/material'

const AppBar = createMuiNode(MuiAppBar)
export default AppBar
