// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Autocomplete as MuiAutocomplete } from '@mui/material'

const Autocomplete = createMuiNode(MuiAutocomplete)
export default Autocomplete
