// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { AvatarGroup as MuiAvatarGroup } from '@mui/material'

const AvatarGroup = createMuiNode(MuiAvatarGroup)
export default AvatarGroup
