// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Avatar as MuiAvatar } from '@mui/material'

const Avatar = createMuiNode(MuiAvatar)
export default Avatar
