// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Badge as MuiBadge } from '@mui/material'

const Badge = createMuiNode(MuiBadge)
export default Badge
