// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { BottomNavigationAction as MuiBottomNavigationAction } from '@mui/material'

const BottomNavigationAction = createMuiNode(MuiBottomNavigationAction)
export default BottomNavigationAction
