// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { BottomNavigation as MuiBottomNavigation } from '@mui/material'

const BottomNavigation = createMuiNode(MuiBottomNavigation)
export default BottomNavigation
