// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Box as MuiBox } from '@mui/material'

const Box = createMuiNode(MuiBox)
export default Box
