// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Breadcrumbs as MuiBreadcrumbs } from '@mui/material'

const Breadcrumbs = createMuiNode(MuiBreadcrumbs)
export default Breadcrumbs
