// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Button as MuiButton } from '@mui/material'

const Button = createMuiNode(MuiButton)
export default Button
