// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ButtonBase as MuiButtonBase } from '@mui/material'

const ButtonBase = createMuiNode(MuiButtonBase)
export default ButtonBase
