// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ButtonGroup as MuiButtonGroup } from '@mui/material'

const ButtonGroup = createMuiNode(MuiButtonGroup)
export default ButtonGroup
