// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { CardMedia as MuiCardMedia } from '@mui/material'

const CardMedia = createMuiNode(MuiCardMedia)
export default CardMedia
