// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { CardHeader as MuiCardHeader } from '@mui/material'

const CardHeader = createMuiNode(MuiCardHeader)
export default CardHeader
