// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { CardContent as MuiCardContent } from '@mui/material'

const CardContent = createMuiNode(MuiCardContent)
export default CardContent
