// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Card as MuiCard } from '@mui/material'

const Card = createMuiNode(MuiCard)
export default Card
