// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { CardActions as MuiCardActions } from '@mui/material'

const CardActions = createMuiNode(MuiCardActions)
export default CardActions
