// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Checkbox as MuiCheckbox } from '@mui/material'

const Checkbox = createMuiNode(MuiCheckbox)
export default Checkbox
