// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Chip as MuiChip } from '@mui/material'

const Chip = createMuiNode(MuiChip)
export default Chip
