// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { CircularProgress as MuiCircularProgress } from '@mui/material'

const CircularProgress = createMuiNode(MuiCircularProgress)
export default CircularProgress
