// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ClickAwayListener as MuiClickAwayListener } from '@mui/material'

const ClickAwayListener = createMuiNode(MuiClickAwayListener)
export default ClickAwayListener
