// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Collapse as MuiCollapse } from '@mui/material'

const Collapse = createMuiNode(MuiCollapse)
export default Collapse
