// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Container as MuiContainer } from '@mui/material'

const Container = createMuiNode(MuiContainer)
export default Container
