// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { CssBaseline as MuiCssBaseline } from '@mui/material'

const CssBaseline = createMuiNode(MuiCssBaseline)
export default CssBaseline
