// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { CssVarsProvider as MuiCssVarsProvider } from '@mui/material'

const CssVarsProvider = createMuiNode(MuiCssVarsProvider)
export default CssVarsProvider
