// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DialogActions as MuiDialogActions } from '@mui/material'

const DialogActions = createMuiNode(MuiDialogActions)
export default DialogActions
