// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DialogTitle as MuiDialogTitle } from '@mui/material'

const DialogTitle = createMuiNode(MuiDialogTitle)
export default DialogTitle
