// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Dialog as MuiDialog } from '@mui/material'

const Dialog = createMuiNode(MuiDialog)
export default Dialog
