// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DialogContentText as MuiDialogContentText } from '@mui/material'

const DialogContentText = createMuiNode(MuiDialogContentText)
export default DialogContentText
