// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Divider as MuiDivider } from '@mui/material'

const Divider = createMuiNode(MuiDivider)
export default Divider
