// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Drawer as MuiDrawer } from '@mui/material'

const Drawer = createMuiNode(MuiDrawer)
export default Drawer
