// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Fab as MuiFab } from '@mui/material'

const Fab = createMuiNode(MuiFab)
export default Fab
