// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Fade as MuiFade } from '@mui/material'

const Fade = createMuiNode(MuiFade)
export default Fade
