// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { FilledInput as MuiFilledInput } from '@mui/material'

const FilledInput = createMuiNode(MuiFilledInput)
export default FilledInput
