// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { FormHelperText as MuiFormHelperText } from '@mui/material'

const FormHelperText = createMuiNode(MuiFormHelperText)
export default FormHelperText
