// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { FormControl as MuiFormControl } from '@mui/material'

const FormControl = createMuiNode(MuiFormControl)
export default FormControl
