// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { FormControlLabel as MuiFormControlLabel } from '@mui/material'

const FormControlLabel = createMuiNode(MuiFormControlLabel)
export default FormControlLabel
