// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GlobalStyles as MuiGlobalStyles } from '@mui/material'

const GlobalStyles = createMuiNode(MuiGlobalStyles)
export default GlobalStyles
