// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Grid as MuiGrid } from '@mui/material'

const Grid = createMuiNode(MuiGrid)
export default Grid
