// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Grow as MuiGrow } from '@mui/material'

const Grow = createMuiNode(MuiGrow)
export default Grow
