// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Icon as MuiIcon } from '@mui/material'

const Icon = createMuiNode(MuiIcon)
export default Icon
