// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { IconButton as MuiIconButton } from '@mui/material'

const IconButton = createMuiNode(MuiIconButton)
export default IconButton
