// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ImageList as MuiImageList } from '@mui/material'

const ImageList = createMuiNode(MuiImageList)
export default ImageList
