// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ImageListItem as MuiImageListItem } from '@mui/material'

const ImageListItem = createMuiNode(MuiImageListItem)
export default ImageListItem
