// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ImageListItemBar as MuiImageListItemBar } from '@mui/material'

const ImageListItemBar = createMuiNode(MuiImageListItemBar)
export default ImageListItemBar
