// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { InitColorSchemeScript as MuiInitColorSchemeScript } from '@mui/material'

const InitColorSchemeScript = createMuiNode(MuiInitColorSchemeScript)
export default InitColorSchemeScript
