// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Input as MuiInput } from '@mui/material'

const Input = createMuiNode(MuiInput)
export default Input
