// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { InputBase as MuiInputBase } from '@mui/material'

const InputBase = createMuiNode(MuiInputBase)
export default InputBase
