// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { InputAdornment as MuiInputAdornment } from '@mui/material'

const InputAdornment = createMuiNode(MuiInputAdornment)
export default InputAdornment
