// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { InputLabel as MuiInputLabel } from '@mui/material'

const InputLabel = createMuiNode(MuiInputLabel)
export default InputLabel
