// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { LinearProgress as MuiLinearProgress } from '@mui/material'

const LinearProgress = createMuiNode(MuiLinearProgress)
export default LinearProgress
