// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Link as MuiLink } from '@mui/material'

const Link = createMuiNode(MuiLink)
export default Link
