// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ListItemText as MuiListItemText } from '@mui/material'

const ListItemText = createMuiNode(MuiListItemText)
export default ListItemText
