// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ListItem as MuiListItem } from '@mui/material'

const ListItem = createMuiNode(MuiListItem)
export default ListItem
