// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ListSubheader as MuiListSubheader } from '@mui/material'

const ListSubheader = createMuiNode(MuiListSubheader)
export default ListSubheader
