// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ListItemSecondaryAction as MuiListItemSecondaryAction } from '@mui/material'

const ListItemSecondaryAction = createMuiNode(MuiListItemSecondaryAction)
export default ListItemSecondaryAction
