// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { List as MuiList } from '@mui/material'

const List = createMuiNode(MuiList)
export default List
