// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ListItemIcon as MuiListItemIcon } from '@mui/material'

const ListItemIcon = createMuiNode(MuiListItemIcon)
export default ListItemIcon
