// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ListItemButton as MuiListItemButton } from '@mui/material'

const ListItemButton = createMuiNode(MuiListItemButton)
export default ListItemButton
