// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ListItemAvatar as MuiListItemAvatar } from '@mui/material'

const ListItemAvatar = createMuiNode(MuiListItemAvatar)
export default ListItemAvatar
