// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { MenuList as MuiMenuList } from '@mui/material'

const MenuList = createMuiNode(MuiMenuList)
export default MenuList
