// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { MenuItem as MuiMenuItem } from '@mui/material'

const MenuItem = createMuiNode(MuiMenuItem)
export default MenuItem
