// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Menu as MuiMenu } from '@mui/material'

const Menu = createMuiNode(MuiMenu)
export default Menu
