// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { MobileStepper as MuiMobileStepper } from '@mui/material'

const MobileStepper = createMuiNode(MuiMobileStepper)
export default MobileStepper
