// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Modal as MuiModal } from '@mui/material'

const Modal = createMuiNode(MuiModal)
export default Modal
