// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { NativeSelect as MuiNativeSelect } from '@mui/material'

const NativeSelect = createMuiNode(MuiNativeSelect)
export default NativeSelect
