// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { NoSsr as MuiNoSsr } from '@mui/material'

const NoSsr = createMuiNode(MuiNoSsr)
export default NoSsr
