// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { OutlinedInput as MuiOutlinedInput } from '@mui/material'

const OutlinedInput = createMuiNode(MuiOutlinedInput)
export default OutlinedInput
