// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Pagination as MuiPagination } from '@mui/material'

const Pagination = createMuiNode(MuiPagination)
export default Pagination
