// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PaginationItem as MuiPaginationItem } from '@mui/material'

const PaginationItem = createMuiNode(MuiPaginationItem)
export default PaginationItem
