// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Paper as MuiPaper } from '@mui/material'

const Paper = createMuiNode(MuiPaper)
export default Paper
