// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PopoverPaper as MuiPopoverPaper } from '@mui/material'

const PopoverPaper = createMuiNode(MuiPopoverPaper)
export default PopoverPaper
