// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PopoverRoot as MuiPopoverRoot } from '@mui/material'

const PopoverRoot = createMuiNode(MuiPopoverRoot)
export default PopoverRoot
