// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Popover as MuiPopover } from '@mui/material'

const Popover = createMuiNode(MuiPopover)
export default Popover
