// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Popper as MuiPopper } from '@mui/material'

const Popper = createMuiNode(MuiPopper)
export default Popper
