// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Portal as MuiPortal } from '@mui/material'

const Portal = createMuiNode(MuiPortal)
export default Portal
