// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Radio as MuiRadio } from '@mui/material'

const Radio = createMuiNode(MuiRadio)
export default Radio
