// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { RadioGroup as MuiRadioGroup } from '@mui/material'

const RadioGroup = createMuiNode(MuiRadioGroup)
export default RadioGroup
