// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Rating as MuiRating } from '@mui/material'

const Rating = createMuiNode(MuiRating)
export default Rating
