// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ScopedCssBaseline as MuiScopedCssBaseline } from '@mui/material'

const ScopedCssBaseline = createMuiNode(MuiScopedCssBaseline)
export default ScopedCssBaseline
