// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Select as MuiSelect } from '@mui/material'

const Select = createMuiNode(MuiSelect)
export default Select
