// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Skeleton as MuiSkeleton } from '@mui/material'

const Skeleton = createMuiNode(MuiSkeleton)
export default Skeleton
