// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { SliderMarkLabel as MuiSliderMarkLabel } from '@mui/material'

const SliderMarkLabel = createMuiNode(MuiSliderMarkLabel)
export default SliderMarkLabel
