// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { SliderMark as MuiSliderMark } from '@mui/material'

const SliderMark = createMuiNode(MuiSliderMark)
export default SliderMark
