// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { SliderRoot as MuiSliderRoot } from '@mui/material'

const SliderRoot = createMuiNode(MuiSliderRoot)
export default SliderRoot
