// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { SliderRail as MuiSliderRail } from '@mui/material'

const SliderRail = createMuiNode(MuiSliderRail)
export default SliderRail
