// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { SliderTrack as MuiSliderTrack } from '@mui/material'

const SliderTrack = createMuiNode(MuiSliderTrack)
export default SliderTrack
