// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { SliderValueLabel as MuiSliderValueLabel } from '@mui/material'

const SliderValueLabel = createMuiNode(MuiSliderValueLabel)
export default SliderValueLabel
