// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Slide as MuiSlide } from '@mui/material'

const Slide = createMuiNode(MuiSlide)
export default Slide
