// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { SnackbarContent as MuiSnackbarContent } from '@mui/material'

const SnackbarContent = createMuiNode(MuiSnackbarContent)
export default SnackbarContent
