// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Snackbar as MuiSnackbar } from '@mui/material'

const Snackbar = createMuiNode(MuiSnackbar)
export default Snackbar
