// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { SpeedDialAction as MuiSpeedDialAction } from '@mui/material'

const SpeedDialAction = createMuiNode(MuiSpeedDialAction)
export default SpeedDialAction
