// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { SpeedDialIcon as MuiSpeedDialIcon } from '@mui/material'

const SpeedDialIcon = createMuiNode(MuiSpeedDialIcon)
export default SpeedDialIcon
