// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { SpeedDial as MuiSpeedDial } from '@mui/material'

const SpeedDial = createMuiNode(MuiSpeedDial)
export default SpeedDial
