// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Stack as MuiStack } from '@mui/material'

const Stack = createMuiNode(MuiStack)
export default Stack
