// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { StepIcon as MuiStepIcon } from '@mui/material'

const StepIcon = createMuiNode(MuiStepIcon)
export default StepIcon
