// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Step as MuiStep } from '@mui/material'

const Step = createMuiNode(MuiStep)
export default Step
