// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { StepButton as MuiStepButton } from '@mui/material'

const StepButton = createMuiNode(MuiStepButton)
export default StepButton
