// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { StepConnector as MuiStepConnector } from '@mui/material'

const StepConnector = createMuiNode(MuiStepConnector)
export default StepConnector
