// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { StepContent as MuiStepContent } from '@mui/material'

const StepContent = createMuiNode(MuiStepContent)
export default StepContent
