// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { StepLabel as MuiStepLabel } from '@mui/material'

const StepLabel = createMuiNode(MuiStepLabel)
export default StepLabel
