// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Stepper as MuiStepper } from '@mui/material'

const Stepper = createMuiNode(MuiStepper)
export default Stepper
