// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { StyledEngineProvider as MuiStyledEngineProvider } from '@mui/material'

const StyledEngineProvider = createMuiNode(MuiStyledEngineProvider)
export default StyledEngineProvider
