// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { SvgIcon as MuiSvgIcon } from '@mui/material'

const SvgIcon = createMuiNode(MuiSvgIcon)
export default SvgIcon
