// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { SwipeableDrawer as MuiSwipeableDrawer } from '@mui/material'

const SwipeableDrawer = createMuiNode(MuiSwipeableDrawer)
export default SwipeableDrawer
