// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Switch as MuiSwitch } from '@mui/material'

const Switch = createMuiNode(MuiSwitch)
export default Switch
