// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Tab as MuiTab } from '@mui/material'

const Tab = createMuiNode(MuiTab)
export default Tab
