// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TableCell as MuiTableCell } from '@mui/material'

const TableCell = createMuiNode(MuiTableCell)
export default TableCell
