// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TableHead as MuiTableHead } from '@mui/material'

const TableHead = createMuiNode(MuiTableHead)
export default TableHead
