// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TableContainer as MuiTableContainer } from '@mui/material'

const TableContainer = createMuiNode(MuiTableContainer)
export default TableContainer
