// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TableRow as MuiTableRow } from '@mui/material'

const TableRow = createMuiNode(MuiTableRow)
export default TableRow
