// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TablePagination as MuiTablePagination } from '@mui/material'

const TablePagination = createMuiNode(MuiTablePagination)
export default TablePagination
