// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TablePaginationActions as MuiTablePaginationActions } from '@mui/material'

const TablePaginationActions = createMuiNode(MuiTablePaginationActions)
export default TablePaginationActions
