// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TableFooter as MuiTableFooter } from '@mui/material'

const TableFooter = createMuiNode(MuiTableFooter)
export default TableFooter
