// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Table as MuiTable } from '@mui/material'

const Table = createMuiNode(MuiTable)
export default Table
