// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TableSortLabel as MuiTableSortLabel } from '@mui/material'

const TableSortLabel = createMuiNode(MuiTableSortLabel)
export default TableSortLabel
