// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Tabs as MuiTabs } from '@mui/material'

const Tabs = createMuiNode(MuiTabs)
export default Tabs
