// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TabScrollButton as MuiTabScrollButton } from '@mui/material'

const TabScrollButton = createMuiNode(MuiTabScrollButton)
export default TabScrollButton
