// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TextField as MuiTextField } from '@mui/material'

const TextField = createMuiNode(MuiTextField)
export default TextField
