// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TextareaAutosize as MuiTextareaAutosize } from '@mui/material'

const TextareaAutosize = createMuiNode(MuiTextareaAutosize)
export default TextareaAutosize
