// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ThemeProvider as MuiThemeProvider } from '@mui/material'

const ThemeProvider = createMuiNode(MuiThemeProvider)
export default ThemeProvider
