// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ToggleButton as MuiToggleButton } from '@mui/material'

const ToggleButton = createMuiNode(MuiToggleButton)
export default ToggleButton
