// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ToggleButtonGroup as MuiToggleButtonGroup } from '@mui/material'

const ToggleButtonGroup = createMuiNode(MuiToggleButtonGroup)
export default ToggleButtonGroup
