// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Tooltip as MuiTooltip } from '@mui/material'

const Tooltip = createMuiNode(MuiTooltip)
export default Tooltip
