// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Typography as MuiTypography } from '@mui/material'

const Typography = createMuiNode(MuiTypography)
export default Typography
