// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Zoom as MuiZoom } from '@mui/material'

const Zoom = createMuiNode(MuiZoom)
export default Zoom
