// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DataGridPremium as MuiDataGridPremium } from '@mui/x-data-grid-pro'

const DataGridPremium = createMuiNode(MuiDataGridPremium)
export default DataGridPremium
