// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DataGrid as MuiDataGrid } from '@mui/x-data-grid-pro'

const DataGrid = createMuiNode(MuiDataGrid)
export default DataGrid
