// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridColumnHeaderMenu as MuiGridColumnHeaderMenu } from '@mui/x-data-grid-pro'

const GridColumnHeaderMenu = createMuiNode(MuiGridColumnHeaderMenu)
export default GridColumnHeaderMenu
