// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridTripleDotsVerticalIcon as MuiGridTripleDotsVerticalIcon } from '@mui/x-data-grid-pro'

const GridTripleDotsVerticalIcon = createMuiNode(MuiGridTripleDotsVerticalIcon)
export default GridTripleDotsVerticalIcon
