// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridColumnIcon as MuiGridColumnIcon } from '@mui/x-data-grid-pro'

const GridColumnIcon = createMuiNode(MuiGridColumnIcon)
export default GridColumnIcon
