// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridBody as MuiGridBody } from '@mui/x-data-grid-pro'

const GridBody = createMuiNode(MuiGridBody)
export default GridBody
