// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridEditLongTextCell as MuiGridEditLongTextCell } from '@mui/x-data-grid-pro'

const GridEditLongTextCell = createMuiNode(MuiGridEditLongTextCell)
export default GridEditLongTextCell
