// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridFilterInputDate as MuiGridFilterInputDate } from '@mui/x-data-grid-pro'

const GridFilterInputDate = createMuiNode(MuiGridFilterInputDate)
export default GridFilterInputDate
