// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridMenuIcon as MuiGridMenuIcon } from '@mui/x-data-grid-pro'

const GridMenuIcon = createMuiNode(MuiGridMenuIcon)
export default GridMenuIcon
