// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridPanel as MuiGridPanel } from '@mui/x-data-grid-pro'

const GridPanel = createMuiNode(MuiGridPanel)
export default GridPanel
