// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridMultiSelectCell as MuiGridMultiSelectCell } from '@mui/x-data-grid-pro'

const GridMultiSelectCell = createMuiNode(MuiGridMultiSelectCell)
export default GridMultiSelectCell
