// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridColumnMenuPinningItem as MuiGridColumnMenuPinningItem } from '@mui/x-data-grid-pro'

const GridColumnMenuPinningItem = createMuiNode(MuiGridColumnMenuPinningItem)
export default GridColumnMenuPinningItem
