// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridEditDateCell as MuiGridEditDateCell } from '@mui/x-data-grid-pro'

const GridEditDateCell = createMuiNode(MuiGridEditDateCell)
export default GridEditDateCell
