// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridKeyboardArrowRight as MuiGridKeyboardArrowRight } from '@mui/x-data-grid-pro'

const GridKeyboardArrowRight = createMuiNode(MuiGridKeyboardArrowRight)
export default GridKeyboardArrowRight
