// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridFooterContainer as MuiGridFooterContainer } from '@mui/x-data-grid-pro'

const GridFooterContainer = createMuiNode(MuiGridFooterContainer)
export default GridFooterContainer
