// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridPanelHeader as MuiGridPanelHeader } from '@mui/x-data-grid-pro'

const GridPanelHeader = createMuiNode(MuiGridPanelHeader)
export default GridPanelHeader
