// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridViewStreamIcon as MuiGridViewStreamIcon } from '@mui/x-data-grid-pro'

const GridViewStreamIcon = createMuiNode(MuiGridViewStreamIcon)
export default GridViewStreamIcon
