// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridDetailPanelToggleCell as MuiGridDetailPanelToggleCell } from '@mui/x-data-grid-pro'

const GridDetailPanelToggleCell = createMuiNode(MuiGridDetailPanelToggleCell)
export default GridDetailPanelToggleCell
