// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridEditSingleSelectCell as MuiGridEditSingleSelectCell } from '@mui/x-data-grid-pro'

const GridEditSingleSelectCell = createMuiNode(MuiGridEditSingleSelectCell)
export default GridEditSingleSelectCell
