// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridColumnMenuSortItem as MuiGridColumnMenuSortItem } from '@mui/x-data-grid-pro'

const GridColumnMenuSortItem = createMuiNode(MuiGridColumnMenuSortItem)
export default GridColumnMenuSortItem
