// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridFooter as MuiGridFooter } from '@mui/x-data-grid-pro'

const GridFooter = createMuiNode(MuiGridFooter)
export default GridFooter
