// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridLongTextCell as MuiGridLongTextCell } from '@mui/x-data-grid-pro'

const GridLongTextCell = createMuiNode(MuiGridLongTextCell)
export default GridLongTextCell
