// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridLongTextCellExpandIcon as MuiGridLongTextCellExpandIcon } from '@mui/x-data-grid-pro'

const GridLongTextCellExpandIcon = createMuiNode(MuiGridLongTextCellExpandIcon)
export default GridLongTextCellExpandIcon
