// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridEditMultiSelectCell as MuiGridEditMultiSelectCell } from '@mui/x-data-grid-pro'

const GridEditMultiSelectCell = createMuiNode(MuiGridEditMultiSelectCell)
export default GridEditMultiSelectCell
