// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridFilterInputValue as MuiGridFilterInputValue } from '@mui/x-data-grid-pro'

const GridFilterInputValue = createMuiNode(MuiGridFilterInputValue)
export default GridFilterInputValue
