// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridClearIcon as MuiGridClearIcon } from '@mui/x-data-grid-pro'

const GridClearIcon = createMuiNode(MuiGridClearIcon)
export default GridClearIcon
