// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridHeader as MuiGridHeader } from '@mui/x-data-grid-pro'

const GridHeader = createMuiNode(MuiGridHeader)
export default GridHeader
