// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridRowReorderCell as MuiGridRowReorderCell } from '@mui/x-data-grid-pro'

const GridRowReorderCell = createMuiNode(MuiGridRowReorderCell)
export default GridRowReorderCell
