// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridHeaderCheckbox as MuiGridHeaderCheckbox } from '@mui/x-data-grid-pro'

const GridHeaderCheckbox = createMuiNode(MuiGridHeaderCheckbox)
export default GridHeaderCheckbox
