// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridCellCheckboxForwardRef as MuiGridCellCheckboxForwardRef } from '@mui/x-data-grid-pro'

const GridCellCheckboxForwardRef = createMuiNode(MuiGridCellCheckboxForwardRef)
export default GridCellCheckboxForwardRef
