// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridEditInputCell as MuiGridEditInputCell } from '@mui/x-data-grid-pro'

const GridEditInputCell = createMuiNode(MuiGridEditInputCell)
export default GridEditInputCell
