// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridDragIcon as MuiGridDragIcon } from '@mui/x-data-grid-pro'

const GridDragIcon = createMuiNode(MuiGridDragIcon)
export default GridDragIcon
