// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridArrowDownwardIcon as MuiGridArrowDownwardIcon } from '@mui/x-data-grid-pro'

const GridArrowDownwardIcon = createMuiNode(MuiGridArrowDownwardIcon)
export default GridArrowDownwardIcon
