// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridNoColumnsOverlay as MuiGridNoColumnsOverlay } from '@mui/x-data-grid-pro'

const GridNoColumnsOverlay = createMuiNode(MuiGridNoColumnsOverlay)
export default GridNoColumnsOverlay
