// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridPushPinRightIcon as MuiGridPushPinRightIcon } from '@mui/x-data-grid-pro'

const GridPushPinRightIcon = createMuiNode(MuiGridPushPinRightIcon)
export default GridPushPinRightIcon
