// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridFilterForm as MuiGridFilterForm } from '@mui/x-data-grid-pro'

const GridFilterForm = createMuiNode(MuiGridFilterForm)
export default GridFilterForm
