// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridDeleteIcon as MuiGridDeleteIcon } from '@mui/x-data-grid-pro'

const GridDeleteIcon = createMuiNode(MuiGridDeleteIcon)
export default GridDeleteIcon
