// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridMoreVertIcon as MuiGridMoreVertIcon } from '@mui/x-data-grid-pro'

const GridMoreVertIcon = createMuiNode(MuiGridMoreVertIcon)
export default GridMoreVertIcon
