// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridHeaderFilterCell as MuiGridHeaderFilterCell } from '@mui/x-data-grid-pro'

const GridHeaderFilterCell = createMuiNode(MuiGridHeaderFilterCell)
export default GridHeaderFilterCell
