// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Toolbar as MuiToolbar } from '@mui/x-data-grid-pro'

const Toolbar = createMuiNode(MuiToolbar)
export default Toolbar
