// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ToolbarButton as MuiToolbarButton } from '@mui/x-data-grid-pro'

const ToolbarButton = createMuiNode(MuiToolbarButton)
export default ToolbarButton
