// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { AppRouterCacheProvider as MuiAppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'

const AppRouterCacheProvider = createMuiNode(MuiAppRouterCacheProvider)
export default AppRouterCacheProvider
