// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { RichTreeViewProRoot as MuiRichTreeViewProRoot } from '@mui/x-tree-view-pro'

const RichTreeViewProRoot = createMuiNode(MuiRichTreeViewProRoot)
export default RichTreeViewProRoot
