// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { RichTreeViewPro as MuiRichTreeViewPro } from '@mui/x-tree-view-pro'

const RichTreeViewPro = createMuiNode(MuiRichTreeViewPro)
export default RichTreeViewPro
