// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TreeViewExpandIcon as MuiTreeViewExpandIcon } from '@mui/x-tree-view-pro'

const TreeViewExpandIcon = createMuiNode(MuiTreeViewExpandIcon)
export default TreeViewExpandIcon
