// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TreeViewCollapseIcon as MuiTreeViewCollapseIcon } from '@mui/x-tree-view-pro'

const TreeViewCollapseIcon = createMuiNode(MuiTreeViewCollapseIcon)
export default TreeViewCollapseIcon
