// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TreeItemLabel as MuiTreeItemLabel } from '@mui/x-tree-view-pro'

const TreeItemLabel = createMuiNode(MuiTreeItemLabel)
export default TreeItemLabel
