// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TreeItemCheckbox as MuiTreeItemCheckbox } from '@mui/x-tree-view-pro'

const TreeItemCheckbox = createMuiNode(MuiTreeItemCheckbox)
export default TreeItemCheckbox
