// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TreeItem as MuiTreeItem } from '@mui/x-tree-view-pro'

const TreeItem = createMuiNode(MuiTreeItem)
export default TreeItem
