// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TreeItemIcon as MuiTreeItemIcon } from '@mui/x-tree-view-pro'

const TreeItemIcon = createMuiNode(MuiTreeItemIcon)
export default TreeItemIcon
