// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { AiAssistantPanelTrigger as MuiAiAssistantPanelTrigger } from '@mui/x-data-grid-premium'

const AiAssistantPanelTrigger = createMuiNode(MuiAiAssistantPanelTrigger)
export default AiAssistantPanelTrigger
