// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ChartsPanelTrigger as MuiChartsPanelTrigger } from '@mui/x-data-grid-premium'

const ChartsPanelTrigger = createMuiNode(MuiChartsPanelTrigger)
export default ChartsPanelTrigger
