// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ColumnsPanelTrigger as MuiColumnsPanelTrigger } from '@mui/x-data-grid-premium'

const ColumnsPanelTrigger = createMuiNode(MuiColumnsPanelTrigger)
export default ColumnsPanelTrigger
