// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DataGridPro as MuiDataGridPro } from '@mui/x-data-grid-premium'

const DataGridPro = createMuiNode(MuiDataGridPro)
export default DataGridPro
