// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ExportPrint as MuiExportPrint } from '@mui/x-data-grid-premium'

const ExportPrint = createMuiNode(MuiExportPrint)
export default ExportPrint
