// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ExportExcel as MuiExportExcel } from '@mui/x-data-grid-premium'

const ExportExcel = createMuiNode(MuiExportExcel)
export default ExportExcel
