// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridExpandLessIcon as MuiGridExpandLessIcon } from '@mui/x-data-grid-premium'

const GridExpandLessIcon = createMuiNode(MuiGridExpandLessIcon)
export default GridExpandLessIcon
