// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridPromptIcon as MuiGridPromptIcon } from '@mui/x-data-grid-premium'

const GridPromptIcon = createMuiNode(MuiGridPromptIcon)
export default GridPromptIcon
