// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridToolbarQuickFilter as MuiGridToolbarQuickFilter } from '@mui/x-data-grid-premium'

const GridToolbarQuickFilter = createMuiNode(MuiGridToolbarQuickFilter)
export default GridToolbarQuickFilter
