// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridFilterInputMultipleMultiSelect as MuiGridFilterInputMultipleMultiSelect } from '@mui/x-data-grid-premium'

const GridFilterInputMultipleMultiSelect = createMuiNode(MuiGridFilterInputMultipleMultiSelect)
export default GridFilterInputMultipleMultiSelect
