// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridFunctionsIcon as MuiGridFunctionsIcon } from '@mui/x-data-grid-premium'

const GridFunctionsIcon = createMuiNode(MuiGridFunctionsIcon)
export default GridFunctionsIcon
