// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridPanelWrapper as MuiGridPanelWrapper } from '@mui/x-data-grid-premium'

const GridPanelWrapper = createMuiNode(MuiGridPanelWrapper)
export default GridPanelWrapper
