// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridLongTextCellCollapseIcon as MuiGridLongTextCellCollapseIcon } from '@mui/x-data-grid-premium'

const GridLongTextCellCollapseIcon = createMuiNode(MuiGridLongTextCellCollapseIcon)
export default GridLongTextCellCollapseIcon
