// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridCellCheckboxRenderer as MuiGridCellCheckboxRenderer } from '@mui/x-data-grid-premium'

const GridCellCheckboxRenderer = createMuiNode(MuiGridCellCheckboxRenderer)
export default GridCellCheckboxRenderer
