// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridPushPinLeftIcon as MuiGridPushPinLeftIcon } from '@mui/x-data-grid-premium'

const GridPushPinLeftIcon = createMuiNode(MuiGridPushPinLeftIcon)
export default GridPushPinLeftIcon
