// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridRoot as MuiGridRoot } from '@mui/x-data-grid-premium'

const GridRoot = createMuiNode(MuiGridRoot)
export default GridRoot
