// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridFilterInputBoolean as MuiGridFilterInputBoolean } from '@mui/x-data-grid-premium'

const GridFilterInputBoolean = createMuiNode(MuiGridFilterInputBoolean)
export default GridFilterInputBoolean
