// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridUndoIcon as MuiGridUndoIcon } from '@mui/x-data-grid-premium'

const GridUndoIcon = createMuiNode(MuiGridUndoIcon)
export default GridUndoIcon
