// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridMicOffIcon as MuiGridMicOffIcon } from '@mui/x-data-grid-premium'

const GridMicOffIcon = createMuiNode(MuiGridMicOffIcon)
export default GridMicOffIcon
