// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridViewHeadlineIcon as MuiGridViewHeadlineIcon } from '@mui/x-data-grid-premium'

const GridViewHeadlineIcon = createMuiNode(MuiGridViewHeadlineIcon)
export default GridViewHeadlineIcon
