// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridLoadingOverlay as MuiGridLoadingOverlay } from '@mui/x-data-grid-premium'

const GridLoadingOverlay = createMuiNode(MuiGridLoadingOverlay)
export default GridLoadingOverlay
