// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridMicIcon as MuiGridMicIcon } from '@mui/x-data-grid-premium'

const GridMicIcon = createMuiNode(MuiGridMicIcon)
export default GridMicIcon
