// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridPivotIcon as MuiGridPivotIcon } from '@mui/x-data-grid-premium'

const GridPivotIcon = createMuiNode(MuiGridPivotIcon)
export default GridPivotIcon
