// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridArrowUpwardIcon as MuiGridArrowUpwardIcon } from '@mui/x-data-grid-premium'

const GridArrowUpwardIcon = createMuiNode(MuiGridArrowUpwardIcon)
export default GridArrowUpwardIcon
