// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridSearchIcon as MuiGridSearchIcon } from '@mui/x-data-grid-premium'

const GridSearchIcon = createMuiNode(MuiGridSearchIcon)
export default GridSearchIcon
