// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridSendIcon as MuiGridSendIcon } from '@mui/x-data-grid-premium'

const GridSendIcon = createMuiNode(MuiGridSendIcon)
export default GridSendIcon
