// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridSyncIcon as MuiGridSyncIcon } from '@mui/x-data-grid-premium'

const GridSyncIcon = createMuiNode(MuiGridSyncIcon)
export default GridSyncIcon
