// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridExcelExportMenuItem as MuiGridExcelExportMenuItem } from '@mui/x-data-grid-premium'

const GridExcelExportMenuItem = createMuiNode(MuiGridExcelExportMenuItem)
export default GridExcelExportMenuItem
