// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridEmptyPivotOverlay as MuiGridEmptyPivotOverlay } from '@mui/x-data-grid-premium'

const GridEmptyPivotOverlay = createMuiNode(MuiGridEmptyPivotOverlay)
export default GridEmptyPivotOverlay
