// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridRerunIcon as MuiGridRerunIcon } from '@mui/x-data-grid-premium'

const GridRerunIcon = createMuiNode(MuiGridRerunIcon)
export default GridRerunIcon
