// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridGenericColumnMenu as MuiGridGenericColumnMenu } from '@mui/x-data-grid-premium'

const GridGenericColumnMenu = createMuiNode(MuiGridGenericColumnMenu)
export default GridGenericColumnMenu
