// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridNoRowsOverlay as MuiGridNoRowsOverlay } from '@mui/x-data-grid-premium'

const GridNoRowsOverlay = createMuiNode(MuiGridNoRowsOverlay)
export default GridNoRowsOverlay
