// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridContextProvider as MuiGridContextProvider } from '@mui/x-data-grid-premium'

const GridContextProvider = createMuiNode(MuiGridContextProvider)
export default GridContextProvider
