// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridChartsIcon as MuiGridChartsIcon } from '@mui/x-data-grid-premium'

const GridChartsIcon = createMuiNode(MuiGridChartsIcon)
export default GridChartsIcon
