// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridPivotPanel as MuiGridPivotPanel } from '@mui/x-data-grid-premium'

const GridPivotPanel = createMuiNode(MuiGridPivotPanel)
export default GridPivotPanel
