// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridColumnMenuContainer as MuiGridColumnMenuContainer } from '@mui/x-data-grid-premium'

const GridColumnMenuContainer = createMuiNode(MuiGridColumnMenuContainer)
export default GridColumnMenuContainer
