// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridTreeDataGroupingCell as MuiGridTreeDataGroupingCell } from '@mui/x-data-grid-premium'

const GridTreeDataGroupingCell = createMuiNode(MuiGridTreeDataGroupingCell)
export default GridTreeDataGroupingCell
