// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridChartsPanel as MuiGridChartsPanel } from '@mui/x-data-grid-premium'

const GridChartsPanel = createMuiNode(MuiGridChartsPanel)
export default GridChartsPanel
