// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridFilterInputSingleSelect as MuiGridFilterInputSingleSelect } from '@mui/x-data-grid-premium'

const GridFilterInputSingleSelect = createMuiNode(MuiGridFilterInputSingleSelect)
export default GridFilterInputSingleSelect
