// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridRowCheckbox as MuiGridRowCheckbox } from '@mui/x-data-grid-premium'

const GridRowCheckbox = createMuiNode(MuiGridRowCheckbox)
export default GridRowCheckbox
