// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridColumnHeaders as MuiGridColumnHeaders } from '@mui/x-data-grid-premium'

const GridColumnHeaders = createMuiNode(MuiGridColumnHeaders)
export default GridColumnHeaders
