// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridRemoveIcon as MuiGridRemoveIcon } from '@mui/x-data-grid-premium'

const GridRemoveIcon = createMuiNode(MuiGridRemoveIcon)
export default GridRemoveIcon
