// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridColumnUnsortedIcon as MuiGridColumnUnsortedIcon } from '@mui/x-data-grid-premium'

const GridColumnUnsortedIcon = createMuiNode(MuiGridColumnUnsortedIcon)
export default GridColumnUnsortedIcon
