// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridHeaderFilterMenu as MuiGridHeaderFilterMenu } from '@mui/x-data-grid-premium'

const GridHeaderFilterMenu = createMuiNode(MuiGridHeaderFilterMenu)
export default GridHeaderFilterMenu
