// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridColumnMenuFilterItem as MuiGridColumnMenuFilterItem } from '@mui/x-data-grid-premium'

const GridColumnMenuFilterItem = createMuiNode(MuiGridColumnMenuFilterItem)
export default GridColumnMenuFilterItem
