// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridAssistantIcon as MuiGridAssistantIcon } from '@mui/x-data-grid-premium'

const GridAssistantIcon = createMuiNode(MuiGridAssistantIcon)
export default GridAssistantIcon
