// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode, type WrappedMui } from '@src/core.js'
import { GridColumnHeaderSortIcon as MuiGridColumnHeaderSortIcon } from '@mui/x-data-grid-premium'

const GridColumnHeaderSortIcon: WrappedMui<typeof MuiGridColumnHeaderSortIcon> = createMuiNode(MuiGridColumnHeaderSortIcon)
export default GridColumnHeaderSortIcon
