// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridAiAssistantPanel as MuiGridAiAssistantPanel } from '@mui/x-data-grid-premium'

const GridAiAssistantPanel = createMuiNode(MuiGridAiAssistantPanel)
export default GridAiAssistantPanel
