// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridHistoryIcon as MuiGridHistoryIcon } from '@mui/x-data-grid-premium'

const GridHistoryIcon = createMuiNode(MuiGridHistoryIcon)
export default GridHistoryIcon
