// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridPagination as MuiGridPagination } from '@mui/x-data-grid-premium'

const GridPagination = createMuiNode(MuiGridPagination)
export default GridPagination
