// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridMoveToTopIcon as MuiGridMoveToTopIcon } from '@mui/x-data-grid-premium'

const GridMoveToTopIcon = createMuiNode(MuiGridMoveToTopIcon)
export default GridMoveToTopIcon
