// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridFilterInputMultipleValue as MuiGridFilterInputMultipleValue } from '@mui/x-data-grid-premium'

const GridFilterInputMultipleValue = createMuiNode(MuiGridFilterInputMultipleValue)
export default GridFilterInputMultipleValue
