// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridCsvExportMenuItem as MuiGridCsvExportMenuItem } from '@mui/x-data-grid-premium'

const GridCsvExportMenuItem = createMuiNode(MuiGridCsvExportMenuItem)
export default GridCsvExportMenuItem
