// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridOverlay as MuiGridOverlay } from '@mui/x-data-grid-premium'

const GridOverlay = createMuiNode(MuiGridOverlay)
export default GridOverlay
