// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridMoveToBottomIcon as MuiGridMoveToBottomIcon } from '@mui/x-data-grid-premium'

const GridMoveToBottomIcon = createMuiNode(MuiGridMoveToBottomIcon)
export default GridMoveToBottomIcon
