// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridHeaderFilterMenuContainer as MuiGridHeaderFilterMenuContainer } from '@mui/x-data-grid-premium'

const GridHeaderFilterMenuContainer = createMuiNode(MuiGridHeaderFilterMenuContainer)
export default GridHeaderFilterMenuContainer
