// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridChartsIntegrationContextProvider as MuiGridChartsIntegrationContextProvider } from '@mui/x-data-grid-premium'

const GridChartsIntegrationContextProvider = createMuiNode(MuiGridChartsIntegrationContextProvider)
export default GridChartsIntegrationContextProvider
