// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridViewColumnIcon as MuiGridViewColumnIcon } from '@mui/x-data-grid-premium'

const GridViewColumnIcon = createMuiNode(MuiGridViewColumnIcon)
export default GridViewColumnIcon
