// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridColumnMenuAggregationItem as MuiGridColumnMenuAggregationItem } from '@mui/x-data-grid-premium'

const GridColumnMenuAggregationItem = createMuiNode(MuiGridColumnMenuAggregationItem)
export default GridColumnMenuAggregationItem
