// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridCloseIcon as MuiGridCloseIcon } from '@mui/x-data-grid-premium'

const GridCloseIcon = createMuiNode(MuiGridCloseIcon)
export default GridCloseIcon
