// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridColumnMenuGroupingItem as MuiGridColumnMenuGroupingItem } from '@mui/x-data-grid-premium'

const GridColumnMenuGroupingItem = createMuiNode(MuiGridColumnMenuGroupingItem)
export default GridColumnMenuGroupingItem
