// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridColumnHeaderTitle as MuiGridColumnHeaderTitle } from '@mui/x-data-grid-premium'

const GridColumnHeaderTitle = createMuiNode(MuiGridColumnHeaderTitle)
export default GridColumnHeaderTitle
