// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridDeleteForeverIcon as MuiGridDeleteForeverIcon } from '@mui/x-data-grid-premium'

const GridDeleteForeverIcon = createMuiNode(MuiGridDeleteForeverIcon)
export default GridDeleteForeverIcon
