// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridToolbarContainer as MuiGridToolbarContainer } from '@mui/x-data-grid-premium'

const GridToolbarContainer = createMuiNode(MuiGridToolbarContainer)
export default GridToolbarContainer
