// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridGroupWorkIcon as MuiGridGroupWorkIcon } from '@mui/x-data-grid-premium'

const GridGroupWorkIcon = createMuiNode(MuiGridGroupWorkIcon)
export default GridGroupWorkIcon
