// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridWorkspacesIcon as MuiGridWorkspacesIcon } from '@mui/x-data-grid-premium'

const GridWorkspacesIcon = createMuiNode(MuiGridWorkspacesIcon)
export default GridWorkspacesIcon
