// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { GridChartsRendererProxy as MuiGridChartsRendererProxy } from '@mui/x-data-grid-premium'

const GridChartsRendererProxy = createMuiNode(MuiGridChartsRendererProxy)
export default GridChartsRendererProxy
