// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PivotPanelTrigger as MuiPivotPanelTrigger } from '@mui/x-data-grid-premium'

const PivotPanelTrigger = createMuiNode(MuiPivotPanelTrigger)
export default PivotPanelTrigger
