// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PromptFieldControl as MuiPromptFieldControl } from '@mui/x-data-grid-premium'

const PromptFieldControl = createMuiNode(MuiPromptFieldControl)
export default PromptFieldControl
