// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PromptFieldSend as MuiPromptFieldSend } from '@mui/x-data-grid-premium'

const PromptFieldSend = createMuiNode(MuiPromptFieldSend)
export default PromptFieldSend
