// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PromptFieldRecord as MuiPromptFieldRecord } from '@mui/x-data-grid-premium'

const PromptFieldRecord = createMuiNode(MuiPromptFieldRecord)
export default PromptFieldRecord
