// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { QuickFilterTrigger as MuiQuickFilterTrigger } from '@mui/x-data-grid-premium'

const QuickFilterTrigger = createMuiNode(MuiQuickFilterTrigger)
export default QuickFilterTrigger
