// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { QuickFilterClear as MuiQuickFilterClear } from '@mui/x-data-grid-premium'

const QuickFilterClear = createMuiNode(MuiQuickFilterClear)
export default QuickFilterClear
