// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { CalendarPickerSkeleton as MuiCalendarPickerSkeleton } from '@mui/lab'

const CalendarPickerSkeleton = createMuiNode(MuiCalendarPickerSkeleton)
export default CalendarPickerSkeleton
