// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { CalendarPicker as MuiCalendarPicker } from '@mui/lab'

const CalendarPicker = createMuiNode(MuiCalendarPicker)
export default CalendarPicker
