// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ClockPicker as MuiClockPicker } from '@mui/lab'

const ClockPicker = createMuiNode(MuiClockPicker)
export default ClockPicker
