// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DateRangePickerDay as MuiDateRangePickerDay } from '@mui/lab'

const DateRangePickerDay = createMuiNode(MuiDateRangePickerDay)
export default DateRangePickerDay
