// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DateRangePicker as MuiDateRangePicker } from '@mui/lab'

const DateRangePicker = createMuiNode(MuiDateRangePicker)
export default DateRangePicker
