// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DateTimePicker as MuiDateTimePicker } from '@mui/lab'

const DateTimePicker = createMuiNode(MuiDateTimePicker)
export default DateTimePicker
