// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DesktopDateRangePicker as MuiDesktopDateRangePicker } from '@mui/lab'

const DesktopDateRangePicker = createMuiNode(MuiDesktopDateRangePicker)
export default DesktopDateRangePicker
