// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { LoadingButton as MuiLoadingButton } from '@mui/lab'

const LoadingButton = createMuiNode(MuiLoadingButton)
export default LoadingButton
