// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Masonry as MuiMasonry } from '@mui/lab'

const Masonry = createMuiNode(MuiMasonry)
export default Masonry
