// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { MobileDatePicker as MuiMobileDatePicker } from '@mui/lab'

const MobileDatePicker = createMuiNode(MuiMobileDatePicker)
export default MobileDatePicker
