// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { MonthPicker as MuiMonthPicker } from '@mui/lab'

const MonthPicker = createMuiNode(MuiMonthPicker)
export default MonthPicker
