// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PickersDay as MuiPickersDay } from '@mui/lab'

const PickersDay = createMuiNode(MuiPickersDay)
export default PickersDay
