// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TabContext as MuiTabContext } from '@mui/lab'

const TabContext = createMuiNode(MuiTabContext)
export default TabContext
