// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TabPanel as MuiTabPanel } from '@mui/lab'

const TabPanel = createMuiNode(MuiTabPanel)
export default TabPanel
