// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TimelineDot as MuiTimelineDot } from '@mui/lab'

const TimelineDot = createMuiNode(MuiTimelineDot)
export default TimelineDot
