// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TimePicker as MuiTimePicker } from '@mui/lab'

const TimePicker = createMuiNode(MuiTimePicker)
export default TimePicker
