// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TimelineOppositeContent as MuiTimelineOppositeContent } from '@mui/lab'

const TimelineOppositeContent = createMuiNode(MuiTimelineOppositeContent)
export default TimelineOppositeContent
