// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TimelineContent as MuiTimelineContent } from '@mui/lab'

const TimelineContent = createMuiNode(MuiTimelineContent)
export default TimelineContent
