// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { Timeline as MuiTimeline } from '@mui/lab'

const Timeline = createMuiNode(MuiTimeline)
export default Timeline
