// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TimelineConnector as MuiTimelineConnector } from '@mui/lab'

const TimelineConnector = createMuiNode(MuiTimelineConnector)
export default TimelineConnector
