// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TimelineSeparator as MuiTimelineSeparator } from '@mui/lab'

const TimelineSeparator = createMuiNode(MuiTimelineSeparator)
export default TimelineSeparator
