// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TreeView as MuiTreeView } from '@mui/lab'

const TreeView = createMuiNode(MuiTreeView)
export default TreeView
