// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { YearPicker as MuiYearPicker } from '@mui/lab'

const YearPicker = createMuiNode(MuiYearPicker)
export default YearPicker
