// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ArrowRightIcon as MuiArrowRightIcon } from '@mui/x-date-pickers-pro'

const ArrowRightIcon = createMuiNode(MuiArrowRightIcon)
export default ArrowRightIcon
