// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { CalendarIcon as MuiCalendarIcon } from '@mui/x-date-pickers-pro'

const CalendarIcon = createMuiNode(MuiCalendarIcon)
export default CalendarIcon
