// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { ClockIcon as MuiClockIcon } from '@mui/x-date-pickers-pro'

const ClockIcon = createMuiNode(MuiClockIcon)
export default ClockIcon
