// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DateRangeCalendar as MuiDateRangeCalendar } from '@mui/x-date-pickers-pro'

const DateRangeCalendar = createMuiNode(MuiDateRangeCalendar)
export default DateRangeCalendar
