// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DateField as MuiDateField } from '@mui/x-date-pickers-pro'

const DateField = createMuiNode(MuiDateField)
export default DateField
