// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DatePicker as MuiDatePicker } from '@mui/x-date-pickers-pro'

const DatePicker = createMuiNode(MuiDatePicker)
export default DatePicker
