// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DateTimeRangePickerToolbar as MuiDateTimeRangePickerToolbar } from '@mui/x-date-pickers-pro'

const DateTimeRangePickerToolbar = createMuiNode(MuiDateTimeRangePickerToolbar)
export default DateTimeRangePickerToolbar
