// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DateCalendar as MuiDateCalendar } from '@mui/x-date-pickers-pro'

const DateCalendar = createMuiNode(MuiDateCalendar)
export default DateCalendar
