// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DateTimeRangePicker as MuiDateTimeRangePicker } from '@mui/x-date-pickers-pro'

const DateTimeRangePicker = createMuiNode(MuiDateTimeRangePicker)
export default DateTimeRangePicker
