// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DayCalendarSkeleton as MuiDayCalendarSkeleton } from '@mui/x-date-pickers-pro'

const DayCalendarSkeleton = createMuiNode(MuiDayCalendarSkeleton)
export default DayCalendarSkeleton
