// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DesktopTimeRangePicker as MuiDesktopTimeRangePicker } from '@mui/x-date-pickers-pro'

const DesktopTimeRangePicker = createMuiNode(MuiDesktopTimeRangePicker)
export default DesktopTimeRangePicker
