// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DesktopDateTimePickerLayout as MuiDesktopDateTimePickerLayout } from '@mui/x-date-pickers-pro'

const DesktopDateTimePickerLayout = createMuiNode(MuiDesktopDateTimePickerLayout)
export default DesktopDateTimePickerLayout
