// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DesktopDatePicker as MuiDesktopDatePicker } from '@mui/x-date-pickers-pro'

const DesktopDatePicker = createMuiNode(MuiDesktopDatePicker)
export default DesktopDatePicker
