// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DesktopDateTimeRangePicker as MuiDesktopDateTimeRangePicker } from '@mui/x-date-pickers-pro'

const DesktopDateTimeRangePicker = createMuiNode(MuiDesktopDateTimeRangePicker)
export default DesktopDateTimeRangePicker
