// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { DigitalClock as MuiDigitalClock } from '@mui/x-date-pickers-pro'

const DigitalClock = createMuiNode(MuiDigitalClock)
export default DigitalClock
