// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { MobileDateRangePicker as MuiMobileDateRangePicker } from '@mui/x-date-pickers-pro'

const MobileDateRangePicker = createMuiNode(MuiMobileDateRangePicker)
export default MobileDateRangePicker
