// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { MobileTimeRangePicker as MuiMobileTimeRangePicker } from '@mui/x-date-pickers-pro'

const MobileTimeRangePicker = createMuiNode(MuiMobileTimeRangePicker)
export default MobileTimeRangePicker
