// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { MobileTimePicker as MuiMobileTimePicker } from '@mui/x-date-pickers-pro'

const MobileTimePicker = createMuiNode(MuiMobileTimePicker)
export default MobileTimePicker
