// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { MobileDateTimeRangePicker as MuiMobileDateTimeRangePicker } from '@mui/x-date-pickers-pro'

const MobileDateTimeRangePicker = createMuiNode(MuiMobileDateTimeRangePicker)
export default MobileDateTimeRangePicker
