// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { MobileDateTimePicker as MuiMobileDateTimePicker } from '@mui/x-date-pickers-pro'

const MobileDateTimePicker = createMuiNode(MuiMobileDateTimePicker)
export default MobileDateTimePicker
