// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { MonthCalendar as MuiMonthCalendar } from '@mui/x-date-pickers-pro'

const MonthCalendar = createMuiNode(MuiMonthCalendar)
export default MonthCalendar
