// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { MultiInputDateTimeRangeField as MuiMultiInputDateTimeRangeField } from '@mui/x-date-pickers-pro'

const MultiInputDateTimeRangeField = createMuiNode(MuiMultiInputDateTimeRangeField)
export default MultiInputDateTimeRangeField
