// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { MultiInputTimeRangeField as MuiMultiInputTimeRangeField } from '@mui/x-date-pickers-pro'

const MultiInputTimeRangeField = createMuiNode(MuiMultiInputTimeRangeField)
export default MultiInputTimeRangeField
