// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { MultiInputDateRangeField as MuiMultiInputDateRangeField } from '@mui/x-date-pickers-pro'

const MultiInputDateRangeField = createMuiNode(MuiMultiInputDateRangeField)
export default MultiInputDateRangeField
