// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PickersFilledInput as MuiPickersFilledInput } from '@mui/x-date-pickers-pro'

const PickersFilledInput = createMuiNode(MuiPickersFilledInput)
export default PickersFilledInput
