// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode, type WrappedMui } from '@src/core.js'
import { PickersActionBar as MuiPickersActionBar } from '@mui/x-date-pickers-pro'

const PickersActionBar: WrappedMui<typeof MuiPickersActionBar> = createMuiNode(MuiPickersActionBar)
export default PickersActionBar
