// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PickersRangeCalendarHeader as MuiPickersRangeCalendarHeader } from '@mui/x-date-pickers-pro'

const PickersRangeCalendarHeader = createMuiNode(MuiPickersRangeCalendarHeader)
export default PickersRangeCalendarHeader
