// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PickersLayoutRoot as MuiPickersLayoutRoot } from '@mui/x-date-pickers-pro'

const PickersLayoutRoot = createMuiNode(MuiPickersLayoutRoot)
export default PickersLayoutRoot
