// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PickersShortcuts as MuiPickersShortcuts } from '@mui/x-date-pickers-pro'

const PickersShortcuts = createMuiNode(MuiPickersShortcuts)
export default PickersShortcuts
