// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { PickersLayout as MuiPickersLayout } from '@mui/x-date-pickers-pro'

const PickersLayout = createMuiNode(MuiPickersLayout)
export default PickersLayout
