// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { SingleInputTimeRangeField as MuiSingleInputTimeRangeField } from '@mui/x-date-pickers-pro'

const SingleInputTimeRangeField = createMuiNode(MuiSingleInputTimeRangeField)
export default SingleInputTimeRangeField
