// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { SingleInputDateTimeRangeField as MuiSingleInputDateTimeRangeField } from '@mui/x-date-pickers-pro'

const SingleInputDateTimeRangeField = createMuiNode(MuiSingleInputDateTimeRangeField)
export default SingleInputDateTimeRangeField
