// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { SingleInputDateRangeField as MuiSingleInputDateRangeField } from '@mui/x-date-pickers-pro'

const SingleInputDateRangeField = createMuiNode(MuiSingleInputDateRangeField)
export default SingleInputDateRangeField
