// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { StaticTimePicker as MuiStaticTimePicker } from '@mui/x-date-pickers-pro'

const StaticTimePicker = createMuiNode(MuiStaticTimePicker)
export default StaticTimePicker
