// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { StaticDateRangePicker as MuiStaticDateRangePicker } from '@mui/x-date-pickers-pro'

const StaticDateRangePicker = createMuiNode(MuiStaticDateRangePicker)
export default StaticDateRangePicker
