// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TimeRangePicker as MuiTimeRangePicker } from '@mui/x-date-pickers-pro'

const TimeRangePicker = createMuiNode(MuiTimeRangePicker)
export default TimeRangePicker
