// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TimePickerToolbar as MuiTimePickerToolbar } from '@mui/x-date-pickers-pro'

const TimePickerToolbar = createMuiNode(MuiTimePickerToolbar)
export default TimePickerToolbar
