// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TimeIcon as MuiTimeIcon } from '@mui/x-date-pickers-pro'

const TimeIcon = createMuiNode(MuiTimeIcon)
export default TimeIcon
