// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TimeRangePickerToolbar as MuiTimeRangePickerToolbar } from '@mui/x-date-pickers-pro'

const TimeRangePickerToolbar = createMuiNode(MuiTimeRangePickerToolbar)
export default TimeRangePickerToolbar
