// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TimeClock as MuiTimeClock } from '@mui/x-date-pickers-pro'

const TimeClock = createMuiNode(MuiTimeClock)
export default TimeClock
