// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { RichTreeView as MuiRichTreeView } from '@mui/x-tree-view'

const RichTreeView = createMuiNode(MuiRichTreeView)
export default RichTreeView
