// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { RichTreeViewRoot as MuiRichTreeViewRoot } from '@mui/x-tree-view'

const RichTreeViewRoot = createMuiNode(MuiRichTreeViewRoot)
export default RichTreeViewRoot
