// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { SimpleTreeView as MuiSimpleTreeView } from '@mui/x-tree-view'

const SimpleTreeView = createMuiNode(MuiSimpleTreeView)
export default SimpleTreeView
