// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TreeItemLabelInput as MuiTreeItemLabelInput } from '@mui/x-tree-view'

const TreeItemLabelInput = createMuiNode(MuiTreeItemLabelInput)
export default TreeItemLabelInput
