// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TreeItemRoot as MuiTreeItemRoot } from '@mui/x-tree-view'

const TreeItemRoot = createMuiNode(MuiTreeItemRoot)
export default TreeItemRoot
