// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TreeItemDragAndDropOverlay as MuiTreeItemDragAndDropOverlay } from '@mui/x-tree-view'

const TreeItemDragAndDropOverlay = createMuiNode(MuiTreeItemDragAndDropOverlay)
export default TreeItemDragAndDropOverlay
