// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TreeItemGroupTransition as MuiTreeItemGroupTransition } from '@mui/x-tree-view'

const TreeItemGroupTransition = createMuiNode(MuiTreeItemGroupTransition)
export default TreeItemGroupTransition
