// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TreeItemContent as MuiTreeItemContent } from '@mui/x-tree-view'

const TreeItemContent = createMuiNode(MuiTreeItemContent)
export default TreeItemContent
