// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TreeItemProvider as MuiTreeItemProvider } from '@mui/x-tree-view'

const TreeItemProvider = createMuiNode(MuiTreeItemProvider)
export default TreeItemProvider
