// Generated by scripts/generate-wrapper-lib.js — do not edit by hand.
import { createMuiNode } from '@src/core.js'
import { TreeItemIconContainer as MuiTreeItemIconContainer } from '@mui/x-tree-view'

const TreeItemIconContainer = createMuiNode(MuiTreeItemIconContainer)
export default TreeItemIconContainer
